# Generated by Django 5.2.5 on 2025-10-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_forgotpasswordrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Handled', 'Handled')], default='Pending', max_length=20),
        ),
    ]
