# Generated by Django 5.2.5 on 2025-11-11 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_forgotpasswordrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgotpasswordrequest',
            name='message',
        ),
    ]
