# Generated by Django 5.2.5 on 2025-11-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_forgotpasswordrequest_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpasswordrequest',
            name='message',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
