# Generated by Django 5.2.5 on 2025-11-11 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_forgotpasswordrequest_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgotpasswordrequest',
            name='message',
        ),
    ]
