# Generated by Django 5.2.5 on 2025-11-01 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockify_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockifyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='clockify_integration.clockifyworkspace')),
            ],
        ),
    ]
