# Generated by Django 5.2.5 on 2025-11-01 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockify_integration', '0002_clockifyuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockifyProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('project_type', models.CharField(max_length=200)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clockify_integration.clockifyworkspace')),
            ],
        ),
    ]
