# Generated by Django 5.2.5 on 2025-11-01 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clockify_integration', '0003_clockifyprojects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clockifyprojects',
            name='project_type',
        ),
    ]
