# Generated by Django 5.2.5 on 2025-11-01 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockify_integration', '0004_remove_clockifyprojects_project_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClockifyUser',
            new_name='ClockifyUsers',
        ),
        migrations.CreateModel(
            name='ClockifyTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_entry_id', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clockify_integration.clockifyprojects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clockify_integration.clockifyusers')),
            ],
            options={
                'verbose_name': 'Time Entry',
                'verbose_name_plural': 'Time Entries',
            },
        ),
    ]
