# Generated by Django 5.2.5 on 2025-11-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockify_integration', '0005_rename_clockifyuser_clockifyusers_clockifytimeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockifytimeentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
