# Generated by Django 5.2.5 on 2025-08-30 14:36

import event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='file',
            field=models.FileField(upload_to=event.models.filter_upload_path, validators=[event.models.validate_filters_file]),
        ),
    ]
