# Generated by Django 5.2.5 on 2025-11-10 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2025)),
                ('month', models.PositiveIntegerField(default=11)),
                ('date', models.PositiveIntegerField(help_text='Day of month (1-31)')),
                ('event', models.CharField(max_length=255)),
                ('clip', models.IntegerField(default=0)),
                ('teamedit', models.IntegerField(default=0)),
                ('indiedit', models.IntegerField(default=0)),
                ('build', models.IntegerField(default=0)),
                ('duration', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', '-date'],
                'unique_together': {('user', 'year', 'month', 'date')},
            },
        ),
    ]
